#!/usr/bin/env python3
"""The check: does the Julia solver compute the same filter as the reference implementation?

    python3 test/verify.py                      # synthetic inputs, generated on the spot
    python3 test/verify.py --inputs DIR         # the same check on the measured inputs
    python3 test/verify.py --solver OTHER.jl    # check some other copy of the solver

`src/RISDesign.jl` and `reference/reference_design.py` are run on the same inputs at 20, 60
and 100 CG iterations and compared.  The exit status is 0 only if every gate passes.

    relative L2 difference at 20 and 60 iterations      < 1e-10       gate
    isolation difference at 100 iterations              < 0.01 dB     gate
    relative L2 difference at 100 iterations            reported, never gated

The last row is the interesting one.  Plain CG loses orthogonality once the extreme Ritz
values converge -- near iteration 75 both on the measured problem and, by design, on the
default synthetic one -- and past that point the iterate is chaotic with respect to
round-off: NumPy changing nothing but its BLAS thread count moves its own 100-iteration
filter by ~1.7e-3 relative, and changing nothing but the FFT grid moves it by ~4e-5, while
the 20- and 60-iteration iterates stay put to 1e-13.  A tight L2 tolerance at iteration
100 would therefore test the round-off of the machine, not the solver.  What does survive
is the physics, so the 100-iteration filters are compared through the isolation metric of
`analysis/metrics.py` -- the number the paper quotes -- at 0.01 dB.

Expect the two gated numbers to move in their last digits between runs.  The reference's
operator comes out a few ulps apart from one process to the next (macOS/arm64, NumPy 1.26),
which after 60 CG iterations shows up in the second digit of a 1e-14 difference -- four orders
under the gate either way.  The solver is the steadier of the two and usually repeats itself
bit for bit, but past the orthogonality wall it is not immune: on the measured inputs one
100-iteration run in about twenty came out 1e-3 from the others, moving the isolation by
0.002 dB.  That is the round-off tail this file gates with physics, not a disagreement.

Everything the default run needs is generated by `test/make_synthetic.py`: no measurement
data, no network, a couple of seconds.  `--inputs` points the same check at a directory
holding the measured `G_ej_2x28x7680_f64le.bin`, `G_jr_101x28x7680_f64le.bin` and
`target_h0_len30717_f64le.bin`; that directory is only read from, and the run needs about
2.5 GB of memory, nearly all of it the reference's unoptimised operator.
"""

import argparse
import os
import re
import subprocess
import sys
import time

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
sys.path[:0] = [HERE, os.path.join(REPO, "reference"), os.path.join(REPO, "analysis")]

import make_synthetic                                   # noqa: E402
import metrics                                          # noqa: E402
from reference_design import design                     # noqa: E402

ITERS = (20, 60, 100)
L2_GATE = 1e-10                 # relative L2, at 20 and 60 iterations only
ISO_GATE = 0.01                 # dB, at 100 iterations

DRIVER = r"""# written by test/verify.py -- run the solver under test on one input directory
include(ARGS[1])
using .RISDesign
indir, outdir = ARGS[2], ARGS[3]
N, K, nE, nR = parse.(Int, ARGS[4:7])
pairs = map(p -> (parse(Int, split(p, ",")[1]), parse(Int, split(p, ",")[2])),
            split(ARGS[8], ";"))
c = parse(Float64, ARGS[9])
legs(name, n) = read!(joinpath(indir, name), Array{Float64}(undef, N, K, n))
G_ej = legs("G_ej_$(nE)x$(K)x$(N)_f64le.bin", nE)
G_jr = legs("G_jr_$(nR)x$(K)x$(N)_f64le.bin", nR)
h0 = read!(joinpath(indir, "target_h0_len$(4N-3)_f64le.bin"), Vector{Float64}(undef, 4N - 3))
for it in parse.(Int, split(ARGS[10], ","))
    t = @elapsed a = design(G_ej, G_jr, h0, pairs, c; maxiter=it)
    open(joinpath(outdir, "a_julia_$(it).bin"), "w") do io
        write(io, a)
    end
    println("julia: maxiter=$it done in $(round(t, digits=1)) s, filter $(size(a))")
    flush(stdout)
end
"""


def shape_of(indir):
    """``(N, K, n_e, n_r)`` of the input set in `indir`, read off the file names.

    Both the generated and the measured sets are named ``G_ej_{n_e}x{K}x{N}_f64le.bin``,
    so one function finds either; the file sizes are checked against the names.
    """
    if not os.path.isdir(indir):
        raise SystemExit(f"{indir}: not a directory")
    found = {}
    for leg in ("G_ej", "G_jr"):
        hits = [m for m in (re.fullmatch(leg + r"_(\d+)x(\d+)x(\d+)_f64le\.bin", f)
                            for f in sorted(os.listdir(indir))) if m]
        if len(hits) != 1:
            raise SystemExit(f"{indir}: expected exactly one {leg}_*x*x*_f64le.bin, found "
                             f"{[m.group(0) for m in hits]}")
        found[leg] = [int(v) for v in hits[0].groups()] + [hits[0].group(0)]
    (n_e, K, N, ej), (n_r, K2, N2, jr) = found["G_ej"], found["G_jr"]
    if (K, N) != (K2, N2):
        raise SystemExit(f"{indir}: {ej} and {jr} disagree on the problem size")
    for name, n in ((ej, n_e), (jr, n_r)):
        size = os.path.getsize(os.path.join(indir, name))
        if size != 8 * n * K * N:
            raise SystemExit(f"{indir}/{name}: {size} bytes, expected {8 * n * K * N}")
    h0 = os.path.join(indir, f"target_h0_len{4 * N - 3}_f64le.bin")
    if not os.path.exists(h0):
        raise SystemExit(f"{indir}: missing {os.path.basename(h0)}")
    return N, K, n_e, n_r


def load(indir, N, K, n_e, n_r):
    """The three inputs as NumPy arrays: ``G_ej (n_e, K, N)``, ``G_jr (n_r, K, N)``, ``h0``."""
    def read(name, shape):
        return np.fromfile(os.path.join(indir, name), dtype="<f8").reshape(shape)
    return (read(f"G_ej_{n_e}x{K}x{N}_f64le.bin", (n_e, K, N)),
            read(f"G_jr_{n_r}x{K}x{N}_f64le.bin", (n_r, K, N)),
            read(f"target_h0_len{4 * N - 3}_f64le.bin", 4 * N - 3))


def default_pairs(n_e, n_r):
    """Routes to design for: the paper's own on the measured set, evenly spread otherwise."""
    if (n_e, n_r) == (2, 101):
        return [(19, 0), (79, 1)]
    return [(round((i + 1) * n_r / (n_e + 1)), i) for i in range(n_e)]


def run_julia(args, indir, workdir, N, K, n_e, n_r, pairs):
    """Run the solver under test at every iteration count; return ``{maxiter: (K, M) filter}``."""
    driver = os.path.join(workdir, "run_solver.jl")
    with open(driver, "w") as fh:
        fh.write(DRIVER)
    cmd = [args.julia, f"-t{args.threads}"]
    if os.path.exists(os.path.join(REPO, "Project.toml")):
        cmd.append("--project=" + REPO)      # the repository pins FFTW.jl there
    cmd += [driver, os.path.abspath(args.solver), indir, workdir,
            str(N), str(K), str(n_e), str(n_r),
            ";".join(f"{j},{i}" for j, i in pairs), repr(args.c),
            ",".join(str(it) for it in ITERS)]
    print(f"running {args.julia} -t{args.threads} on the solver ...", flush=True)
    if subprocess.run(cmd).returncode != 0:
        raise SystemExit("the Julia run failed, see its message above; if a package is missing, "
                         "install the ones this repository pins with\n"
                         "    julia --project=. -e 'using Pkg; Pkg.instantiate()'")
    return {it: np.fromfile(os.path.join(workdir, f"a_julia_{it}.bin"),
                            dtype=np.float64).reshape(K, 2 * N - 1) for it in ITERS}


def run_reference(G_ej, G_jr, h0, pairs, c):
    """Run `reference/reference_design.py` at every iteration count; same return shape."""
    out = {}
    for it in ITERS:
        t0 = time.time()
        out[it] = design(G_ej, G_jr, h0, pairs, c, maxiter=it)
        print(f"reference: maxiter={it} done in {time.time() - t0:.1f} s, "
              f"filter {out[it].shape}", flush=True)
    return out


def report(rows, iso_ref, iso_jl):
    """Print the criterion table and the note, and return True if every gate passed."""
    print(f"\n{'criterion':<44}{'measured':>10} {'':<3}{'threshold':>14}{'result':>8}")
    print("-" * 80)
    for text, measured, unit, gate in rows:
        limit = "not a gate" if gate is None else f"< {gate:g} {unit}".strip()
        result = "info" if gate is None else ("PASS" if measured < gate else "FAIL")
        print(f"{text:<44}{measured:>10.2e} {unit:<3}{limit:>14}{result:>8}")
    print("-" * 80)
    show = dict(precision=4, floatmode="fixed")
    print(f"isolation per emitter [dB]: reference {np.array2string(iso_ref, **show)}, "
          f"solver {np.array2string(iso_jl, **show)}")
    print("The 100-iteration L2 row is information, not a gate: plain CG loses orthogonality near\n"
          "iteration 75, after which round-off alone -- a BLAS thread count, an FFT grid -- moves\n"
          "the filter (by ~1e-3 on the measured inputs), so the physics gates it, one row above.")
    return all(gate is None or measured < gate for _, measured, _, gate in rows)


def main():
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--inputs", metavar="DIR",
                   help="directory of measured inputs; default: generate synthetic ones")
    p.add_argument("--solver", metavar="FILE", default=os.path.join(REPO, "src", "RISDesign.jl"),
                   help="the Julia solver to check (default: the repository's)")
    p.add_argument("--workdir", metavar="DIR", default=make_synthetic.DEFAULT_DIR,
                   help="where inputs and filters are kept; reused between runs")
    p.add_argument("--pairs", metavar="j,i;j,i",
                   help="0-based (receiver, emitter) routes; default: see default_pairs")
    p.add_argument("--c", type=float, default=0.1, help="weight of the unrouted pairs")
    p.add_argument("--threads", type=int, default=min(4, os.cpu_count() or 1),
                   help="Julia threads (the filter does not depend on how many)")
    p.add_argument("--julia", default="julia", help="the Julia executable")
    args = p.parse_args()

    workdir = os.path.abspath(args.workdir)
    os.makedirs(workdir, exist_ok=True)
    indir = os.path.abspath(args.inputs) if args.inputs else workdir
    if not args.inputs:
        d = make_synthetic.DEFAULTS
        if all(os.path.exists(os.path.join(indir, f)) for f in make_synthetic.filenames(
                d["samples"], d["emitters"], d["receivers"], d["transceivers"])):
            print(f"reusing the synthetic inputs in {indir}")
        else:
            paths = make_synthetic.write(indir, *make_synthetic.make())
            print("generated " + ", ".join(os.path.basename(q) for q in paths) + f" in {indir}")

    N, K, n_e, n_r = shape_of(indir)
    pairs = ([tuple(int(v) for v in q.split(",")) for q in args.pairs.split(";")]
             if args.pairs else default_pairs(n_e, n_r))
    print(f"inputs {indir}\n  N={N} transceivers={K} emitters={n_e} receivers={n_r} "
          f"filter taps M={2 * N - 1}\n  routes (receiver, emitter) {pairs}, c={args.c}, "
          f"iterations {ITERS}\nsolver {os.path.abspath(args.solver)}")

    G_ej, G_jr, h0 = load(indir, N, K, n_e, n_r)
    jl = run_julia(args, indir, workdir, N, K, n_e, n_r, pairs)
    ref = run_reference(G_ej, G_jr, h0, pairs, args.c)

    def l2(it):
        return float(np.linalg.norm(ref[it] - jl[it]) / np.linalg.norm(jl[it]))

    iso_ref, iso_jl = (metrics.isolation(metrics.energies(G_ej, G_jr, f[100]), pairs)
                       for f in (ref, jl))
    rows = [(f"relative L2 difference, {it:3d} CG iterations", l2(it), "", L2_GATE)
            for it in ITERS if it != 100]
    rows.append(("isolation difference, 100 CG iterations",
                 float(np.max(np.abs(iso_ref - iso_jl))), "dB", ISO_GATE))
    rows.append(("relative L2 difference, 100 CG iterations", l2(100), "", None))

    ok = report(rows, iso_ref, iso_jl)
    print("\nAll criteria PASS: the solver reproduces the reference implementation." if ok else
          "\nFAILED: the solver does not reproduce the reference implementation.")
    if l2(20) < L2_GATE <= l2(60):
        print("(20 iterations agree and 60 do not, which is also what a problem too small for\n"
              "this check looks like: its wall arrives before iteration 60.  How big is big\n"
              "enough is in test/make_synthetic.py.)")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
